### ISSUE TITLE
Undefined is the message

### ISSUE THREAD

**Issue by w2jeffrey** [aurovrata/cf7-grid-layout#2]
Hi, I installed your newly published CF7 Smart Grid, when I activated and trying to use it, I have an undefined and the "tools" didn't show up as shown in your screen capture.

tested in Win 7: Chrome and Firefox
Sierra / Safari

Best,
Jeff

**Comment by aurovrata** [comment]
did you install the latest version from the WordPress [repo](https://wordpress.org/plugins/cf7-grid-layout/)?

Can you be a little more specific and explain what you mean by 'undefined', is this a js error in your console?

I don't understand what you mean by "tools", the screenshots on the WP plugin page show the admin editor (a UI editor and an html markup editor).  Are you able to see these editors? If not check your js console to see if you are getting any errors.
