### ISSUE TITLE
v4.11 beta 4 - resource path nice-select js and css - 404 error

### ISSUE THREAD

**Issue by detra** [aurovrata/cf7-grid-layout#22]
Odd error, an fyi,

.js and css  resources for nice-select
point to these paths, in wordpress, when beta is active ... 

../plugins/assets/jquery-nice-select/js/jquery.nice-select.min.js?ver=1.1.0
&
../plugins/assets/jquery-nice-select/css/nice-select.css?ver=1.1.0

instead of 
/plugins/cf7-grid-layout-4.11beta4/assets/...

via 
@delbot

**Comment by detra** [comment]
dug a bit deeper into the beta (**v4.11 beta 4**)

lines 1768 & 1779 in 
> ..public/class-cf7-grid-layout-public.php

`$plugin_dir = plugin_dir_url( __DIR__ );` 
changed to 
`$plugin_dir = plugin_dir_url( __FILE__ );` 
fixed it for me @ my end

`$plugin_dir = plugin_dir_url( __DIR__ );` is used elsewhere on lines 180 and 232 - no error from those 

Using the beta to test if issues I'm experiencing - via my support query on WP, resolve or have a fix - then again
it could be me making errors or not using plugin correctly ( great plugin, btw 👍 )

Support query:
[https://wordpress.org/support/topic/accordion-toggle-and-nice-select-issues/](url)

@detra

**Comment by aurovrata** [comment]
thanks for the report.  Nice-select is actually going to be deprecated, the libraries will still be included but not used by the plugin moving forward.

It is being replaced by [hybrid-dropdown](https://github.com/aurovrata/hybrid-html-dropdown) js plugin, a project I have been working on and which is going to bring a lot of interesting additional functionality to dropdown fields for cf7 forms.

> $plugin_dir = plugin_dir_url( __FILE__ );
> fixed it  for me @ my end

thanks I will fix this :)
