### ISSUE TITLE
CF7 Smart Grid Extension +Redirection for Contact Form 7 rnonce issue

### ISSUE THREAD

**Issue by wizardcoder** [aurovrata/cf7-grid-layout#23]
If you have "CF7 Smart Grid Design Extension" and "Redirection for Contact Form 7" enabled, it prevents contact forms from being saved. The following error message will be displayed: "The link you followed has expired."

This appears to be the result of an incorrect nonce name as shown below.

wpcf7-redirect/templates/extensions/extensions-table.php - **Line 10**:

This:  wp_nonce_field( ‘manage_cf7_redirect’, ‘**_wpcf7nonce**’ );
Should be:  wp_nonce_field( ‘manage_cf7_redirect’, ‘**_wpcf7rnonce**’ );

**Comment by wizardcoder** [comment]
Sorry, wrong plugin.

**Comment by aurovrata** [comment]
>If you have "CF7 Smart Grid Design Extension" and "Redirection for Contact Form 7" enabled, it prevents contact forms from being saved. The following error message will be displayed: "The link you followed has expired."

You don't need an extra plugin to redirect.  the Smart Grid-layout extension already provides redirectino functionality within the form editor itself, look for the redirection metabox below the form editor itself.

**Comment by wizardcoder** [comment]
> > If you have "CF7 Smart Grid Design Extension" and "Redirection for Contact Form 7" enabled, it prevents contact forms from being saved. The following error message will be displayed: "The link you followed has expired."
> 
> You don't need an extra plugin to redirect. the Smart Grid-layout extension already provides redirectino functionality within the form editor itself, look for the redirection metabox below the form editor itself.

CF7 Smart Grid Design Extension redirect option only does a redirect to specific pages, with no additional control. Redirection for Contact Form 7 is capable of redirecting a custom URLs such as PDFs and has additional options such as opening in a new tab. There are also options to Pass all the fields from the form as URL query parameters, Pass specific fields from the form as URL query parameters, Encode passed query parameters and adding a delay before the redirect occurs.

There are also many other options such as Fire JavaScript, Save Lead, Send Email, Honeypot, Conditional Logic (Purchase), Create PDF (Purchase), PayPal Integration (Purchase), Stripe Integration (Purchase), API Integrations (Purchase), Custom Validations (Purchase), Thank You Popup (Purchase), Create Posts (Purchase), Custom Login Forms (Purchase), Custom Registration Forms (Purchase), Subscribe to Mailchimp (Purchase), Salesforce Integration (Purchase), Hubspot Integration (Purchase), Actions Bundle (Purchase).

The (purchase) options are additional extensions to Redirection for Contact Form 7, however even the base plugin has much more flexibility than the redirect option in CF7 Smart Grid Design Extension.

P.S. I have contacted the developer of Redirection for Contact Form 7 in regards to the issue with their plugin.

**Comment by aurovrata** [comment]
Fair enough, that's indded quite a powerful plugin!
>P.S. I have contacted the developer of Redirection for Contact Form 7 in regards to the issue with their plugin.
Can you link the issue you raised with them on this thread so I can take a look?
