### ISSUE TITLE
Smart Grid CSS overwrites Custom CSS

### ISSUE THREAD

**Issue by Stefan2409** [aurovrata/cf7-grid-layout#24]
Hello!

I've found the following problem with the plugin:
If I setlup a new form with custom css styles, I cannot change the submit button layout, background, etc. without using the !important tag because the cf7-grid-layout/public/css/min/cf7-grid-layout-public.css gets inserted after the custom css styles and therefore overwrites my styles.

So it should be the case that the custom css styles get loaded after the included ones so that everything can be changed.

**Comment by aurovrata** [comment]
> So it should be the case that the custom css styles get loaded after the included ones so that everything can be changed.

No.  This issue can easily be resolved with either proper enqueueing your file or better understanding of how to overrule existing css rules.

The github repo is for plugin development, reporting bugs, or discussing new functionality.

If you need help, please use the plugin support form on the Wordpress site.
