### ISSUE TITLE
bug hybrid dropdown

### ISSUE THREAD

**Issue by oscarmoreta** [aurovrata/cf7-grid-layout#25]
The last version has an error 

the variable $form must be e

      cf7Forms.not('div.cf7_2_post form.wpcf7-form').each(function(){
        $('.cf7sg-dynamic_checkbox', **$form**).each(function(){
          new HybridDropdown(this, $(this).cf7sgHybridddOptions());
        })
      })

**Comment by aurovrata** [comment]
>must be e

e or this?

**Comment by aurovrata** [comment]
fixed in v4.12.2
