### ISSUE TITLE
dynamic-dropdown field is failed

### ISSUE THREAD

**Issue by ShenHsu** [aurovrata/cf7-grid-layout#40]
When I create a dynamic-dropdown field, and make sure there's no blank space in front of "filter" as below screenshot, red highlight.
![img01](https://github.com/aurovrata/cf7-grid-layout/assets/36794328/1ca901fb-1951-4f43-b950-04829f38325c)

I press the insert tag and then find there's a blank space in front of "filter", but I don't known why...
![img02](https://github.com/aurovrata/cf7-grid-layout/assets/36794328/d2e75f75-9ea8-4965-98a2-60511bb07c9a)

The blank space will cause the warning as follow. It shows the 'Warning Undefined array key "source" in C:\...', and the dynamic-dropdown field is failed.
![img04](https://github.com/aurovrata/cf7-grid-layout/assets/36794328/95d38114-f643-479f-af15-fe4d3075e85d)
![img03](https://github.com/aurovrata/cf7-grid-layout/assets/36794328/c9821407-0eba-4af9-90b0-639bf8f04cee)

This problem can be temporarily solved if I deliberately remove the blank space in the inserted tag.
![img05](https://github.com/aurovrata/cf7-grid-layout/assets/36794328/9e11bd1a-8578-494c-98f5-256519efbabe)

**Comment by aurovrata** [comment]
Thank you for reporting this issue,

> I press the insert tag and then find there's a blank space in front of "filter", but I don't known why...

however this should not be happening.  The js script hard codes the value `"source:filter"` which is inserted as is in the editor.  

Can you try to create a new form and insert the dynamic list with a custom filter source to see if you can repeat the issue?

**Comment by aurovrata** [comment]
I haven't heard back from you, so I am assuming this is no longer an issue.  If you are still facing an issue, please add your observations below and I will reopen the issue.  For now I am closing it.
