### ISSUE TITLE
Ajax and Styles of CF7 is not loading

### ISSUE THREAD

**Issue by dangercris** [aurovrata/cf7-grid-layout#6]
When active de plugin the default CSS and JS functions of CF7 not load in the site

**Comment by Birmania** [comment]
Hi @dangercris,

Personally, I am on the latest version of the plugin installed on my WP 4.9.8 and everything seems O.K for JS and CSS.
Do you have any cache plugin enabled ? If yes, did you try to flush or disable to check if it solve something ?

Note that the JS and CSS are only loaded on 'wpcf7_contact_form' post types, so if you do not see CSS/JS on every page of your website, it is normal.

Yours faithfully,
Birmania

**Comment by aurovrata** [comment]
Hi @dangercris, can you please use the WP support forum for support questions.  This way other people can find similar problems and answers in a single location.  GitHub is for code repo adn bug tracking/fixing + PRs specifically.  If you found a bug in the code then by all means report it here.  For general support I will not entertain any questions here.

@Birmania thanks for helping out with the support :)
