### ISSUE TITLE
Semicolon missing cf7sg-post-form-submit.php

### ISSUE THREAD

**Issue by altworks** [aurovrata/cf7-grid-layout#7]
Missing semicolon on line 76 of  cf7-grid-layout/admin/partials/helpers/cf7sg-post-form-submit.php

**Comment by aurovrata** [comment]
thanks!.  Fixed.  Did you manage to get the table layout working for your mail tags?

**Comment by altworks** [comment]
@aurovrata Unfortunately no. I'm not really sure how to configure it though. I get...

```
<div><label>row(1):</label><span>Mr</span></div>
<div><label>row(2):</label><span>Mrs</span></div>
<div><label>row(1):</label><span>John</span></div>
<div><label>row(2):</label><span>Jane</span></div>
<div><label>row(1):</label><span></span></div>
```

... whether I leave it unaltered **_or_** if I try to configure it with all 9 fields I have in the table.
I'm not sure if this is due to my limited coding knowledge, or if a bit more documentation would help me understand how to set it up.

*Let me know if you would rather me open a thread on wordpress.org

**Comment by aurovrata** [comment]
I replied on the WP support thread
