### ISSUE TITLE
Field inside toggle always displayed in mail

### ISSUE THREAD

**Issue by Birmania** [aurovrata/cf7-grid-layout#9]
Hi @aurovrata,

I notice a little regression with the latest version (2.7.1) compared to the version I was on previously (2.4.1).
In the working version, the fields located in disabled toggle while submitting form was not displayed in the mail sent. (With option to exclude lines where e-mail tag is empty)
In the latest version, they are always displayed even if the toggle is collapsed. In this case, the value of the field is its name.

Working : 2.4.1
Broken : 2.7.1

**Comment by aurovrata** [comment]
oh, I see, thanks for highlighting this.  Will run a few tests and report back.

**Comment by aurovrata** [comment]
HI Birmania, I forgot to ask you, has this been fixed satisfactorily?  I remember doing some work on this and testing it on my local machine but I am not sure why I didn't close the issue here, so could you let me know if is working for you now?
